In [1]:
import numpy as np

In [4]:
np.zeros(shape = (1, 4))

array([[0., 0., 0., 0.]])

In [3]:
np.arange(2, 4)

array([2, 3])

In [4]:
np.arange(2, 12, 2)

array([ 2,  4,  6,  8, 10])

In [5]:
type(0)

int

In [6]:
type(0.)

float

In [7]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.random.seed(101)
arr = np.random.randint(0, 100, 8)
arr

array([95, 11, 81, 70, 63, 87, 75,  9])

In [11]:
arr2 = np.random.randint(0, 100, 8)
arr2

array([77, 40,  4, 63, 40, 60, 92, 64])

In [13]:
arr.max()

95

In [14]:
arr.min()

9

In [15]:
arr.argmax()

0

In [16]:
arr.argmin()

7

In [17]:
arr.argsort()

array([7, 1, 4, 3, 6, 2, 5, 0])

In [19]:
arr.mean()

61.375

In [20]:
arr.shape

(8,)

In [22]:
arr.reshape((2, 4))

array([[95, 11, 81, 70],
       [63, 87, 75,  9]])

In [26]:
mat = np.arange(0, 30).reshape((3, 10))

In [27]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [31]:
col = 2
row = 2

In [33]:
mat[row, col]

22

In [36]:
mat[2, :]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [39]:
mat[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [44]:
#change array values for 0
arr = np.arange(0, 25).reshape((5, 5))
arr[0:5, 2] = 0
arr

array([[ 0,  1,  0,  3,  4],
       [ 5,  6,  0,  8,  9],
       [10, 11,  0, 13, 14],
       [15, 16,  0, 18, 19],
       [20, 21,  0, 23, 24]])

In [45]:
copyArr = arr.copy()
copyArr

array([[ 0,  1,  0,  3,  4],
       [ 5,  6,  0,  8,  9],
       [10, 11,  0, 13, 14],
       [15, 16,  0, 18, 19],
       [20, 21,  0, 23, 24]])